# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: crichton_dummy_development
  username: root
  password: 
  host: localhost
  pool: 5
  timeout: 5000
  encoding: utf8
  variables:
    storage_engine: InnoDB
  
  
test:
  adapter: mysql2
  database: crichton_dummy_test
  username: root
  password: 
  host: localhost
  pool: 5
  timeout: 5000
  encoding: utf8
  variables:
    storage_engine: InnoDB
  
  
production:
  adapter: mysql2
  database: crichton_dummy_production
  username: root
  password: 
  host: localhost
  pool: 5
  timeout: 5000
  encoding: utf8
  variables:
    storage_engine: InnoDB
  